### PR TITLE
Aragon Flock proposal: Aragon Black

### PR DESCRIPTION
**Pull request by osarrouy**
# Aragon Black 

## Summary

**Aragon Black** is a team whose core members come majoritarily from the **PandoNetwork** team [mostly known in the ecosystem for the development of the pando protocol]. The PandoNetwork team has been working closely with the Aragon ecosystem for almost a year now and has been the recipient of two Aragon Nest grants.

To strengthen its commitment to the Aragon movement, the PandoNetwork team has decided to **apply to the Flock program as Aragon Black**. This first Flock proposal covers six months of work. However, if the Aragon community lends us its trust, we intend to re-apply to this program on the long run.

To cover its operating costs for six months [Q3 & Q4 2019] and contribute creating a thriving Aragon ecosystem, Aragon Black requests:

- \$450k paid in DAI [or any other stable assets].
- 125k ANT for incentivization purposes.

[Read the full proposal →](https://github.com/AragonBlack/flock/blob/master/teams/Aragon%20Black/2019%20-%20Q3%20%26%20Q4.md)

### CODE REVIEW

**Comment by stefanobernardi** [comment]
Hello AragonBlack team! We’d love to approve your PR soon and see you submit a Finance Track AGP before next week’s deadline on the 11th!

One quick suggestion we think would make it easier for the community in understanding the value proposition: reorder I01 (Decentralized VCS) and I03 (Apiary) in your proposal by order of priority. We say this after reviewing forum discussions and the feedback you received there.

Another topic: the ANT grant. Framing it in that big number might be a scary view, I know it is for me! As it approaches 10% of the size of the treasury.
We appreciate the fact that ANT grants are hard to size, and that up to this point we have seen other flock teams do it that way.

What I think might make more sense is to frame it as a per year per person amount, and the association would either be the one deploying the vesting contracts or make sure that those grants are paid when needed.
The reason is that granting a large amount to one organization without being it tied to a specific number of people or similar is not the best way.

Keen to have thoughts around this, but otherwise ready to approve so you can submit the AGP soon!

**Comment by osarrouy** [comment]
Hey @stefanobernardi,

Thanks a lot for your feedback. We are going to update the proposal accordingly, keep it up-to-date with our latest news [pando on Rinkeby, etc.] and add team bios as requested on the Aragon Forum thread.

On the ANT grant topic your remark makes a lot of sense. We kind of took inspiration from other teams to size it without taking in consideration all the details [duration, etc.]. We realize now it makes a lot of money for a six-mont long grant and will update the proposal! The ANT grant per capita per year mechanism makes a lot of sense too.

We should have the proposal updated by tomorrow or sunday.

Thanks again.

**Comment by osarrouy** [comment]
Hey @stefanobernardi,

The proposal is now updated with respect to the topics discussed above. Daniel is in the US now but he should sign the agreement too as soon as he wakes up!

Thanks again.

**Comment by stefanobernardi** [comment]
Thanks!

One caveat around the ANT is that we think we might overhaul in general the incentivization policy globally, and apply the same to every flock team - this policy would obviously be approved / updated by the network.

We can for the meantime pre-approve as is, but wanted to mention this topic - as we're currently exploring it. It would reduce a lot of cognitive load for users and also for teams.

Lastly, I think we might want to think about making the AGP last 3 months to start OR, in case of a successful vote, think about coming up with a renewal proposal in the immediate next AGP ballot. 
This is a highly complex topic, involving actual people's lives, so I'd be happy to chat more on the phone / live about how to best structure it.

For full disclosure: Autark also has had its own grant divided in two chunks. (Reason being that it's a substantial part of the treasury, and just too high of a risk for the Association to give such a large grant with no particular contractual recourse.)

In any case I think we can approve the Github flock proposal as-is, and then finalize a few last things at the AGP level.

**Pull request merged**
