### PR TITLE
DEPRECATED: Aragon Flock Proposal: Native

### PR DESCRIPTION
**Pull request by proofoftom**
This is a deprecated first draft. Please see v2 of our Aragon Flock Proposal: https://github.com/aragon/flock/pull/11
<hr />

# <p align="center">Aragon Flock Proposal</p>

## **Summary**

[Native](https://nativeproject.one/) is building a financial ecosystem for a collaborative world. We provide tools and infrastructure for community-based organizations to incentivize their members, scale in size, and realize their value in ways not possible through the traditional financial economy.

Since its inception, Native has intended to use Aragon as a backend for each of its communities by leveraging the modular implementations that Aragon provides in the form of Templates and Apps. The decision to proceed with this integration was made after an internal set of governance tools were created for the Native prototype and once it was clear that Aragon would now be able to meet the needs of our organizations.

This provides a unique opportunity for cross-pollination between the two networks, where Native will contribute to arApps that will be useful within the greater DAO ecosystem.

We humbly request the following to cover six months (and the long term sustainability) of operating funds:

* 600k DAI, with milestone check-ins (coming soon)
* 600k ANT with 1-year cliff and 4-year vesting

[Read the Full Proposal →](https://github.com/Native-Protocol/flock/blob/master/teams/Native/2019Q2-3.md)

[Discuss on Native's Forum →](https://forum.nativeproject.one/)

[Discuss on Aragon's Forum →](https://forum.aragon.org/t/aragon-flock-proposal-native/658)

[Native Chat →](https://chat.nativeproject.one/)

### CODE REVIEW

**Comment by izqui** [comment]
Amazing proposal, thanks!

You mention the NTV token multiple times, which I assume it is the Native token. Can you talk a bit about the token? How it will be initially distributed and what does it do?

PS: You may want to create a thread in the Aragon Forum [as Aragon Black did](https://forum.aragon.org/t/aragon-flock-proposal-aragon-black/646/4) and have the conversation there, as whenever this is merged it will go out view.

**Comment by proofoftom** [comment]
Thanks for the quick reply @izqui! We actually created a whole forum with each initiative as a topic - to keep the noise out of yours - that one can find here: https://forum.nativeproject.one/

**Comment by proofoftom** [comment]
But to your point, perhaps we create a cross thread of sorts? I'll let @JakeVartanian speak to the tokenomics when he's around in a few 😃

**Comment by izqui** [comment]
@proofoftom neat! I think a general thread in the Aragon Forum would be interesting regardless.

**Comment by proofoftom** [comment]
For those whom are interested, the cross thread on Aragon's forums can be found here: https://forum.aragon.org/t/aragon-flock-proposal-native/658

**Comment by jackfrutaco** [comment]
@izqui  - thanks for the kind words about the proposal.

Regarding Native Token (NTV), let’s start with what it does:

Native Token is the [base currency](https://www.investopedia.com/terms/b/basecurrency.asp) for all of the communities within the Native ecosystem. Having a base currency for all community tokens has many benefits including:

1. Provides a consistent framework to value all communities against each other and provide fair/accurate pricing without needing to be added to an exchange.

2. Easy liquidity back to other tokens - an NTV pool will have more opportunities for liquidity than a single community token.

3. Encapsulates the network value of the Native ecosystem - what is Native as a whole worth at any moment?

4. Can peg the asset to a basket of other tokens - example DAI, ANT, ETH, (DOT??) - and can optimize what we and our communities believe to be the ideal portfolio for a network reserve currency.

5. We can leverage the smart token model to provide a partial reserve in any of the assets chosen for the basket to - see reserve ratios (discussed more below related to the 2SAAM model discussed in I01)

6. The Native model provides an ongoing calculation of price for each token at any time based on the amount of liquidity and reserve in the network at any time.

7. Reserve ratios can be modified depending on the status of the Native ecosystem and the broader market at the time. Higher volatility = less backed and less volatility = more backed.

8. Perhaps the most important (depending on one’s values) is that using a common base token for all tokens in the network creates an anti-rivalrous system which means that communities are incentivized to collaborate rather than compete. When one community grows, all communities benefit. Beyond scope of response to get more detailed here, but will do so in a Medium post soon.

------------
Now for the questions that could come up:

**Why don’t you just use ETH?**

We love ETH. It’s a great network token, and we would definitely consider using it as a partial base for NTV over the short term. The challenge with using purely ETH as a base is that there are so many factors that lead to ETH volatility, and many of them will have nothing to do with the Native ecosystem. We want to filter our exposure to external variables of volatility.

**Why don’t you just use DAI?**

We love DAI. It’s a great stable token, and we are definitely using DAI as a significant portion of our base in the early days of the Native Ecosystem. There are way fewer factors contributing to volatility, and USD is a commonly spent currency around the world which communities can spend their operating capital without being scared that they may not be able to pay their next bills. But we wouldn’t want to limit ourselves to only having DAI as a base as that limits opportunities for synergy between networks (like ANT perhaps). Also what happens when there is that economic collapse? We want to have the freedom to debase and rebase as the ecosystem sees fit.

**Why don’t you just use ANT?**

We love ANT. It’s a great network and governance (and other things soon) token. We would love to use ANT as a partial base for NTV once Native stabilizes and there is a large enough liquidity pool. Maybe ANT decides to adopt this model and use NTV as a partial base too one day. Then organizations/communities launched on either network benefit both networks to a degree. 

**Why would you fractionally reserve an asset? Isn’t that, like, how we ended up with the housing crises and the crazy financial economy we are in today?**

In the 2SAAM model that the Native Token uses, any deposits made into the NTV contract (to generate new tokens) are split between the reserve and the operating fund. The percentage splits can be modified. 

Let’s think about an ICO. ICOs technically also have a split - it just happens to be 100% to the fund and 0% to the reserve. The only way a market is made from a traditional ICO is when a market/liquidity is built on an exchange. If a market never gets built, everyone is screwed and could end up with zero. 

In the case of the 2SAAM model, let’s say we use a 50/50 split and $1k comes into the contract. $500 goes to operating fund, $500 goes to the reserve, and 1k worth of project tokens are issued.

This is where it gets tricky, so bear with me.

A 100% backed reserve would mean that you are only guaranteed to get $0.50 on the dollar back, which is okay, but not really an accurate assessment of the value of the asset. The asset value also has to take into consideration cash on hand (or money in the fund) and the future potential value of that money being utilized effectively.

_Future potential value of money being utilized effectively is the only indicator of price in most ICOs to date_

So, what happens if we back this token with a 50% reserve (this is just for easy number's sake and answering the question and not factual ratios for NTV)? 

In the case of a $500 reserve that is 50% backed, the total market cap of the asset would be $1,000 (which makes more sense because of the total amount that has gone into the contract). An even lower than 50% reserve would indicate that the team should be able to execute super well or are in their growth stage which is a volatile time naturally where the group needs more capital and is less concerned about stability. A local community just trying to use the local currency for their economy would be on the opposite side of the reserve spectrum.

The price moves like a bonding curve (and like a bid/ask spread on order book): more tokens sold at once = lower price per token and vice versa. Reserve ratio decides how quickly that price moves.

Both the Native Token and each Community Token leverage this model, which leads us to templates (I03) and the ability to create fair valuations of organizations/communities (I05). What is the optimal reserve ratio for a token at any time? Does it depend on the type of community? Maybe what stage of a lifecycle an organization is in? We will help provide recommendations for these ratios to community organizers and their choices will be one KPI in creating a comprehensive grade/valuation of the community/organization.

To conclude on this one - leverage is tricky, but when utilized effectively can be a more beneficial situation for all parties involved. At Native, it is our goal to find the most useful and safe ratios for both Native Token and all of our communities.

**This doesn’t need a token! All tokens are useless! Scam!**

That’s not a question, real critique, or helpful comment. Would encourage critical thinking and learning about the nature of a “unit of account” and why they are helpful in economics. Value transfer is like speech, and each “unit of account” and therefore token is its own language.

Following the crowd and popular opinion in the contemporary moment is not the path. Read books.

-----

This was a lot. Please let me know what is clear and what isn’t. Happy to dive deeper into this if desired.

Once we are clear on this part, I will move into the distribution, which hopefully will be trivial compared to this.

**Comment by stefanobernardi** [comment]
Deprecated, closing

**Pull request closed without merging**
